package rere.ql.options

trait AllOptions
  extends Classes
  with BoundsOptions
  with InterleaveOptions
  with IndexOptions
  with OrderedIndexOptions
  with RandomOptions
  with DefaultOptions
  with OrderingOptions
  with DurabilityOptions
  with ReturnChangesOptions
  with NonAtomicOptions
  with EmitOptions
  with ConflictOptions
  with PrimaryKeyOptions
  with ShardsOptions
  with ReplicasOptions
  with WaitOptions
  with TimeoutOptions
  with DryRunOptions
  with EmergencyRepairOptions
  with IndexTypeOptions
  with OverwriteOptions
  with DefaultTimezoneOptions
  with GroupMultiplicityOptions
  with ChangesOptions
  with GeoSystemOptions
  with DistanceUnitOptions
  with NumVerticesOptions
  with CircleFillOptions
  with MaxResultsOptions
  with MaxDistanceOptions
  with ReadModeOptions
  with IdentifierFormatOptions
  with JSTimeoutOptions
  with HttpTimeoutOptions
  with HttpAttemptsOptions
  with HttpRedirectsOptions
  with HttpVerifyOptions
  with HttpResultFormatOptions
  with HttpMethodOptions
  with HttpAuthOptions
  with HttpParamsOptions
  with HttpHeaderOptions
  with HttpDataOptions
  with HttpPaginationOptions
  with ProfileOptions
  with NoreplyOptions
  with ArrayLimitOptions
  with MinBatchRowsOptions
  with MaxBatchRowsOptions
  with MaxBatchBytesOptions
  with MaxBatchSecondsOptions
  with FirstBatchScaledownFactorOptions
